kind: Pod
apiVersion: v1
metadata:
  name: etcd
  namespace: kube-system
  labels:
    openshift.io/control-plane: "true"
    openshift.io/component: etcd
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
  - name: etcd
    image: {{ .Image }}
    imagePullPolicy: {{ .ImagePullPolicy }}
    securityContext:
      runAsNonRoot: false
      privileged: true
    workingDir: /var/run/etcd/data
    command: ["/usr/local/bin/etcd"]
    args:
    - --ca-file=/var/run/etcd/tls/root-ca.crt
    - --trusted-ca-file=/var/run/etcd/tls/etcd-client-ca.crt
    - --client-cert-auth
    - --cert-file=/var/run/etcd/tls/etcd-server.crt
    - --key-file=/var/run/etcd/tls/etcd-server.key
    - --listen-client-urls=https://0.0.0.0:2379
    - --advertise-client-urls=https://0.0.0.0:2379
    - --data-dir=/var/run/etcd/data
    volumeMounts:
    - mountPath: /var/run/etcd/tls
      name: tls
      readOnly: true
    - mountPath: /var/run/etcd/data
      name: data
  volumes:
  - name: tls
    hostPath:
      path: {{ .TlsDir }}
  - name: data
    hostPath:
      path: {{ .EtcdDataDir }}